package id.actaca.dsas.environment

interface BaseEnvironment {
    var  argument7:Int
    var  argument8:Int
    var  argument9:Int
    var  argument_relative:Int
    var  background_alpha:Int
    var  background_blend:Int
    var  background_color:Int
    var  background_foreground:Int
    var  background_height:Int
    var  background_hspeed:Int
    var  background_htiled:Int
    var  background_index:Int
    var  background_showcolor:Int
    var  background_visible:Int
    var  background_vspeed:Int
    var  background_vtiled:Int
    var  background_width:Int
    var  background_x:Int
    var  background_xscale:Int
    var  background_y:Int
    var  background_yscale:Int
    var  caption_health:Int
    var  caption_lives:Int
    var  caption_score:Int
    var  current_day:Int
    var  current_hour:Int
    var  current_minute:Int
    var  current_month:Int
    var  current_second:Int
    var  current_time:Int
    var  current_weekday:Int
    var  current_year:Int
    var  cursor_sprite:Int
    var  debug_mode:Int
    var  error_last:Int
    var  error_occurred:Int
    var  event_action:Int
    var  event_number:Int
    var  event_object:Int
    var  event_type:Int
    var  fps:Int
    var  game_id:Int
    var  gamemaker_pro:Int
    var  gamemaker_registered:Int
    var  gamemaker_version:Int
    var  health:Int
    var  instance_count:Int
    var  instance_id:Int
    var  keyboard_key:Int
    var  keyboard_lastchar:Int
    var  keyboard_lastkey:Int
    var  keyboard_string:Int
    var  lives:Int
    var  mouse_button:Int
    var  mouse_lastbutton:Int
    var  mouse_x:Int
    var  mouse_y:Int
    var  program_directory:Int
    var  room:Int
    var  room_caption:Int
    var  room_first:Int
    var  room_height:Int
    var  room_last:Int
    var  room_persistent:Int
    var  room_speed:Int
    var  room_width:Int
    var  score:Int
    var  secure_mode:Int
    var  show_health:Int
    var  show_lives:Int
    var  show_score:Int
    var  temp_directory:Int
    var  transition_color:Int
    var  transition_kind:Int
    var  transition_steps:Int
    var  view_angle:Int
    var  view_current:Int
    var  view_enabled:Int
    var  view_hborder:Int
    var  view_hport:Int
    var  view_hspeed:Int
    var  view_hview:Int
    var  view_object:Int
    var  view_vborder:Int
    var  view_visible:Int
    var  view_vspeed:Int
    var  view_wport:Int
    var  view_wview:Int
    var  view_xport:Int
    var  view_xview:Int
    var  view_yport:Int
    var  view_yview:Int
    var  working_director:Int
}